packaging: add snap
Change-Id: I5b24b809cec3763c44808fe9f056cba862336531

diff --git a/Makefile.packaging b/Makefile.packaging
--- a/Makefile.packaging
+++ b/Makefile.packaging
@@ -118,12 +118,24 @@ package-all: package-debian_9 \
              package-opensuse-leap_15.1 \
              package-opensuse-leap_15.2 \
              package-opensuse-tumbleweed \
-             package-gentoo
+             package-gentoo \
+             package-snap
+
 
 # Append the output of make-packaging-target to this Makefile
 # see Makefile.packaging.distro_targets
 $(shell scripts/make-packaging-target.py --generate-all > Makefile.packaging.distro_targets)
 include Makefile.packaging.distro_targets
+
+docker/Dockerfile_snap: patches/docker-snap-build-scripts.patch
+	if patch -p1 -fR --dry-run < $< >/dev/null 2>&1; then \
+	  echo "Patching $@... skipped (already patched)"; \
+	else \
+	  echo "Patching $@..."; \
+	  patch -p1 -Ns < $< || { echo "Patching $@... failed" >&2 && exit 1; }; \
+	  echo "Patching $@... done"; \
+	fi
+.PHONY: docker/Dockerfile_snap
 
 ###################
 ## Other targets ##
